# This is a development Docker Compose file.
# It is intended for development purposes only and should not be used as a production example.
# Misuse in production environments may lead to unexpected behavior or security risks.

networks:
  lingarr:
    driver: bridge

services:
  Lingarr.Server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: Lingarr.Server
    image: ${DOCKER_REGISTRY-}lingarrserver
    build:
      context: .
      dockerfile: Lingarr.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION=sqlite
      - SERVICE_TYPE=libretranslate
      - SOURCE_LANGUAGES=[{"name":"English","code":"en"},{"name":"Dutch","code":"nl"}]
      - TARGET_LANGUAGES=[{"name":"Turkish","code":"tr"},{"name":"Dutch","code":"nl"}]
      - ASPNETCORE_URLS=http://+:9876
      - ASPNETCORE_HTTP_PORTS=9876
    volumes:
      - ./.temp-data/movies:/movies
      - ./.temp-data/series:/series
      - ./.temp-data/config/lingarr:/app/config
    ports:
      - "9877:9876"
    networks:
      - lingarr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./.temp-data/movies:/movies
      - ./.temp-data/config/radarr:/config
    restart: unless-stopped
    ports:
      - "7878:7878"
    networks:
      - lingarr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./.temp-data/series:/series
      - ./.temp-data/config/sonarr:/config
    restart: unless-stopped
    ports:
      - "8989:8989"
    networks:
      - lingarr

